openapi: 3.0.3
info:
  title: Swagger Student
  description: Manage Student.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  /user/create-user:
    $ref: "./user/CreateUser.yaml"
  /user/login:
    $ref: "./user/Login.yaml"
  /student/create-student:
    $ref: "./student/CreateStudent.yaml"
  /student/update-student:
    $ref: "./student/UpdateStudent.yaml"
  /student/get-all-student/page={page}:
    $ref: "./student/GetAllStudent.yaml"