openapi: 3.0.3
info:
  title: Swagger Student
  description: Manage Student.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  /user/create-user:
    $ref: "./user/CreateUser.yaml"
  /user/login:
    $ref: "./user/Login.yaml"